### ISSUE TITLE
[Refactoring] 사용되지 않는 SampleController 제거

### ISSUE THREAD

**Issue by marcel1315** [TrainingDiary/training-diary-backend#82]
### 📝 개요
- 응답 공통화 예시를 보여주기 위해 만들었던 SampleController 제거 필요

### ✅ 작업할 내용
- SampleController 및 여기서 사용하는 예제 DTO 제거

**Comment by kyoo0115** [comment]
혹시 이슈 해결 되었나요?

**Comment by marcel1315** [comment]
아직 작업 전입니다
